# -*- coding: utf-8 -*-
"""Go_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qb0IRzjTzJonYMP9S4Tt7WXVVq5lrg2T
"""

import os
import subprocess 

if os.path.isfile("bot_utils/telegram_token.py")== True:
    os.remove("bot_utils/telegram_token.py")
f = open("bot_utils/telegram_token.py", 'x')
print('Введите токен вашего бота:')
answer = input()
f.write("token_my =  '%s'" % (str(answer)))
f.close()

subprocess.Popen('bot.py')