# -*- coding: utf-8 -*-
"""token.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uv5-YU3zVAmZ-mg3Al8Khe5Je9P9pP2t
"""

token = 865302346:AAHXfjDVupav7QsqqWta3p8QQCvAIhsJsCA